graph TD
    org.apache:apache:33 --> org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin}
    org.apache:apache:33 --> org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin}
    org.apache:apache:33 --> org.codehaus.plexus:plexus-utils:${version.plexus-utils}
    org.apache:apache:33 --> org.codehaus.plexus:plexus-xml:${version.plexus-xml}
    org.apache:apache:33 --> org.junit:junit-bom:${versions.junit5}
