graph TD
    org.junit.platform:junit-platform-suite-commons:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-launcher:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-jfr:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-engine:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-console:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.jupiter:junit-jupiter-params:5.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.jupiter:junit-jupiter-migrationsupport:5.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-testkit:1.10.3 --> org.junit:junit-bom:5.10.3
    org.apache:apache:33 --> org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin}
    org.apache:apache:33 --> org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin}
    org.apache:apache:33 --> org.codehaus.plexus:plexus-utils:${version.plexus-utils}
    org.apache:apache:33 --> org.codehaus.plexus:plexus-xml:${version.plexus-xml}
    org.apache:apache:33 --> org.junit:junit-bom:${versions.junit5}
    org.junit.platform:junit-platform-suite:1.10.3 --> org.junit:junit-bom:5.10.3
    org.codehaus.plexus:plexus-utils:${version.plexus-utils} --> org.codehaus.plexus:plexus-xml:3.0.0
    org.codehaus.plexus:plexus-utils:${version.plexus-utils} --> org.junit.jupiter:junit-jupiter-api:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> com.google.inject:guice:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> org.slf4j:slf4j-api:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> org.osgi:osgi.core:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> javax.annotation:javax.annotation-api:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> javax.enterprise:cdi-api:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> javax.servlet:servlet-api:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> com.google.inject.extensions:guice-servlet:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> junit:junit:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> org.junit.jupiter:junit-jupiter-api:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> org.testng:testng:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> ch.qos.logback:logback-classic:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> com.google.inject.extensions:guice-assistedinject:
    org.eclipse.sisu:org.eclipse.sisu.inject:${version.sisu-maven-plugin} --> org.apache.felix:org.apache.felix.framework:
    org.junit.vintage:junit-vintage-engine:5.10.3 --> org.junit:junit-bom:5.10.3
    org.openjdk.jmh:jmh-core:1.37 --> junit:junit:
    org.openjdk.jmh:jmh-core:1.37 --> net.sf.jopt-simple:jopt-simple:
    org.openjdk.jmh:jmh-core:1.37 --> org.apache.commons:commons-math3:
    org.junit.jupiter:junit-jupiter:5.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-suite-api:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-runner:1.10.3 --> org.junit:junit-bom:5.10.3
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> com.google.inject:guice:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> javax.annotation:javax.annotation-api:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> javax.enterprise:cdi-api:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> org.eclipse.sisu:org.eclipse.sisu.inject:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> org.codehaus.plexus:plexus-component-annotations:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> org.codehaus.plexus:plexus-classworlds:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> org.codehaus.plexus:plexus-utils:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> org.codehaus.plexus:plexus-xml:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> org.slf4j:slf4j-api:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> org.osgi:osgi.core:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> junit:junit:
    org.eclipse.sisu:org.eclipse.sisu.plexus:${version.sisu-maven-plugin} --> ch.qos.logback:logback-classic:
    org.openjdk.jmh:jmh-generator-annprocess:1.37 --> org.openjdk.jmh:jmh-core:
    org.codehaus.plexus:plexus-xml:3.0.0 --> org.codehaus.plexus:plexus-utils:4.0.0
    org.codehaus.plexus:plexus-xml:3.0.0 --> org.openjdk.jmh:jmh-core:1.36
    org.codehaus.plexus:plexus-xml:3.0.0 --> org.openjdk.jmh:jmh-generator-annprocess:1.36
    org.codehaus.plexus:plexus-xml:3.0.0 --> junit:junit:4.13.2
    org.junit.platform:junit-platform-commons:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.jupiter:junit-jupiter:5.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.jupiter:junit-jupiter-api:5.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.jupiter:junit-jupiter-engine:5.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.jupiter:junit-jupiter-migrationsupport:5.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.jupiter:junit-jupiter-params:5.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-commons:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-console:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-engine:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-jfr:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-launcher:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-reporting:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-runner:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-suite:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-suite-api:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-suite-commons:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-suite-engine:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.platform:junit-platform-testkit:1.10.3
    org.junit:junit-bom:${versions.junit5} --> org.junit.vintage:junit-vintage-engine:5.10.3
    org.codehaus.plexus:plexus-xml:${version.plexus-xml} --> org.openjdk.jmh:jmh-core:1.37
    org.codehaus.plexus:plexus-xml:${version.plexus-xml} --> org.openjdk.jmh:jmh-generator-annprocess:1.37
    org.codehaus.plexus:plexus-xml:${version.plexus-xml} --> org.junit.jupiter:junit-jupiter:
    org.codehaus.plexus:plexus-xml:${version.plexus-xml} --> org.codehaus.plexus:plexus-utils:4.0.1
    org.codehaus.plexus:plexus-utils:4.0.1 --> org.codehaus.plexus:plexus-xml:3.0.0
    org.codehaus.plexus:plexus-utils:4.0.1 --> org.junit.jupiter:junit-jupiter-api:
    org.junit.jupiter:junit-jupiter-engine:5.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-suite-engine:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.platform:junit-platform-reporting:1.10.3 --> org.junit:junit-bom:5.10.3
    org.junit.jupiter:junit-jupiter-api:5.10.3 --> org.junit:junit-bom:5.10.3
